# .github/workflows/build.yml
name: Build PyInstaller bundles

on:
  push:
    tags:
      - 'v*.*.*'      # on version tags like v1.2.3
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.13]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Run PyInstaller
      run: |
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          pyinstaller --onefile --windowed --name keyboard_trap main.py
        else
          pyinstaller --onefile --name keyboard_trap.exe main.py
        fi

    - name: Collect build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: |
          dist/keyboard_trap.app        # macOS bundle
          dist/keyboard_trap.exe       # Windows executable
